# Generated by Django 4.2.2 on 2023-06-20 00:24

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="conteudo",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 19, 20, 24, 3, 859907)
            ),
        ),
    ]
